# Generated by Django 4.2.1 on 2023-05-22 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='nome')),
                ('data_of_register', models.DateField(default=datetime.datetime(2023, 5, 21, 22, 37, 12, 938437), verbose_name='data de Início')),
            ],
            options={
                'verbose_name': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('themes', models.ManyToManyField(related_name='themes_on_courses', to='produtos.theme', verbose_name='disciplinas')),
            ],
            options={
                'verbose_name': 'curso',
            },
        ),
    ]
