# Generated by Django 4.1.7 on 2023-05-22 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='data_of_register',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 0, 12, 58, 657655), verbose_name='data de Início'),
        ),
    ]
