# Generated by Django 4.2.6 on 2023-10-05 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_group_data_of_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='data_of_register',
            field=models.DateField(default=datetime.datetime(2023, 10, 5, 14, 44, 24, 389430), verbose_name='data de Início'),
        ),
    ]
